version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-stretch-node
        environment:
          IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build docker image
        command: |
          docker build --rm=false -t $IMAGE_NAME:$CIRCLE_BUILD_NUM .
          docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $DOCKER_PRIVATE_REPO
          docker tag -f $IMAGE_NAME:$CIRCLE_BUILD_NUM $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest
          docker tag -f $IMAGE_NAME:$CIRCLE_BUILD_NUM $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(git describe --tags --always)
          docker tag -f $IMAGE_NAME:$CIRCLE_BUILD_NUM $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(git rev-parse --verify  HEAD)

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
        requires:
          - build
        filters:
          branches:
            only:
              master
          tags:
            only: /.*/